//
// Created by wangzhengcheng on 2017/10/11.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include "common_audio/vad/include/webrtc_vad.h"

#include <stdlib.h>
#include <string.h>

#include "common_audio/signal_processing/include/signal_processing_library.h"
#include "common_audio/vad/vad_core.h"
#include "typedefs.h"  // NOLINT(build/include)

#include "Platform.h"

static const int kInitCheck = 42;
static const int kValidRates[] = { 8000, 16000, 32000, 48000 };
static const size_t kRatesSize = sizeof(kValidRates) / sizeof(*kValidRates);
static const int kMaxFrameLengthMs = 30;
static VadInstT* self = NULL;

static OsInt16 *micBuf = NULL;
/* Header for class com_wzc_vad_VadUtils */

#ifndef _Included_com_wzc_vad_VadUtils
#define _Included_com_wzc_vad_VadUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wzc_vad_VadUtils
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wzc_vad_VadUtils_create
   (JNIEnv *env, jobject obj){

      self = (VadInstT *) malloc(sizeof(VadInstT));
      micBuf = (OsInt16*)malloc(sizeof(OsInt16)*80);

      WebRtcSpl_Init();
      self->init_flag = 0;
  }

/*
 * Class:     com_wzc_vad_VadUtils
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wzc_vad_VadUtils_free
   (JNIEnv *env, jobject obj){
      free(self);
  }

/*
 * Class:     com_wzc_vad_VadUtils
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wzc_vad_VadUtils_init
  (JNIEnv *env, jobject obj){
      return WebRtcVad_InitCore((VadInstT*) self);
  }

/*
 * Class:     com_wzc_vad_VadUtils
 * Method:    setMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wzc_vad_VadUtils_setMode
  (JNIEnv *env, jobject obj,jint mode){

  if (self->init_flag != kInitCheck) {
  return -1;
  }

  return WebRtcVad_set_mode_core(self, mode);

  }

/*
 * Class:     com_wzc_vad_VadUtils
 * Method:    process
 * Signature: (I[SI)I
 */
JNIEXPORT jint JNICALL Java_com_wzc_vad_VadUtils_process
  (JNIEnv *env, jobject obj, jint fs, jshortArray buffer, jint length){
  int vad = -1;

  if (self->init_flag != kInitCheck) {
  return -1;
  }
  if (buffer == NULL) {
  return -2;
  }
  if (WebRtcVad_ValidRateAndFrameLength(fs, length) != 0) {
  return -3;
  }

  (*env)->GetShortArrayRegion(env,buffer,0,80,micBuf);

  if (fs == 48000) {
  vad = WebRtcVad_CalcVad48khz(self, micBuf, length);
  } else if (fs == 32000) {
  vad = WebRtcVad_CalcVad32khz(self, micBuf, length);
  } else if (fs == 16000) {
  vad = WebRtcVad_CalcVad16khz(self, micBuf, length);
  } else if (fs == 8000) {
  vad = WebRtcVad_CalcVad8khz(self, micBuf, length);
  }

  if (vad > 0) {
  vad = 1;
  }
  return vad;
  }

/*
 * Class:     com_wzc_vad_VadUtils
 * Method:    validRateAndFrameLength
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wzc_vad_VadUtils_validRateAndFrameLength
  (JNIEnv *env, jobject obj, jint fs, jint length){
  int return_value = -1;
  size_t i;
  int valid_length_ms;
  size_t valid_length;

  // We only allow 10, 20 or 30 ms frames. Loop through valid frame rates and
  // see if we have a matching pair.
      for (i = 0; i < kRatesSize; i++) {
          if (kValidRates[i] == fs) {
              for (valid_length_ms = 10; valid_length_ms <= kMaxFrameLengthMs;
                  valid_length_ms += 10) {
                  valid_length = (size_t)(kValidRates[i] / 1000 * valid_length_ms);
                  if (length == valid_length) {
                      return_value = 0;
                      break;
                  }
              }
              break;
          }
      }

      return return_value;
  }

#ifdef __cplusplus
}
#endif
#endif
